name: Backend CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  S3_BUCKET: employeeapplicationdst
  BACKEND_ZIP: backend.zip


jobs:

 backend-build:

  name: Build Backend
  runs-on: ubuntu-latest

  steps:

    - name: Checkout code
      uses: actions/checkout@v4


    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
        cache-dependency-path: app/backend/package-lock.json


    - name: Install dependencies
      working-directory: app/backend
      run: npm ci


    - name: Validate Backend
      working-directory: app/backend
      run: |
        node --check src/server.js


    - name: Run tests
      working-directory: app/backend
      run: |
        if npm run | grep -q "test"; then
          npm test
        else
          echo "No tests configured, skipping"
        fi


    - name: Create backend package
      run: |
        cd app/backend

        zip -r ../../${{ env.BACKEND_ZIP }} . \
        -x "node_modules/*" \
        -x "*.log"

        cd ../..

        echo "Checking zip file:"
        ls -lh ${{ env.BACKEND_ZIP }}

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
       role-to-assume: arn:aws:iam::843089371063:role/github-actions-role
       aws-region: ${{ env.AWS_REGION }}