name: Backend CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  S3_BUCKET: employeeapplicationdst
  BACKEND_ZIP: backend.zip


jobs:

 backend-build:

  name: Build Backend
  runs-on: ubuntu-latest

  steps:

    - name: Checkout code
      uses: actions/checkout@v4


    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
        cache-dependency-path: app/backend/package-lock.json


    - name: Install dependencies
      working-directory: app/backend
      run: npm ci


    - name: Validate Backend
      working-directory: app/backend
      run: |
        node --check src/server.js


    - name: Run tests
      working-directory: app/backend
      run: |
        if npm run | grep -q "test"; then
          npm test
        else
          echo "No tests configured, skipping"
        fi


    - name: Create backend package
      run: |
        cd app/backend

        zip -r ../../${{ env.BACKEND_ZIP }} . \
        -x "node_modules/*" \
        -x "*.log"

        cd ../..

        echo "Checking zip file:"
        ls -lh ${{ env.BACKEND_ZIP }}

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
       role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
       aws-region: ${{ env.AWS_REGION }}
    
    - name: Verify AWS identity
      run: aws sts get-caller-identity

    - name: Verify AWS identity
      run: |
       aws sts get-caller-identity


    - name: Upload backend zip to S3
      run: |
        aws s3 cp ${{ env.BACKEND_ZIP }} \
        s3://${{ env.S3_BUCKET }}/${{ env.BACKEND_ZIP }}


    - name: Verify S3 upload
      run: |
       aws s3 ls s3://${{ env.S3_BUCKET }}/

    - name: Deploy to EC2 using SSM
      run: |
        COMMAND_ID=$(aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=tag:Name,Values=employee-backend" \
          --parameters 'commands=[
            "mkdir -p /opt/backend",
            "cd /opt/backend",
            "aws s3 cp s3://'${{ env.S3_BUCKET }}'/'${{ env.BACKEND_ZIP }}' .",
            "rm -rf app",
            "mkdir app",
            "unzip -o backend.zip -d app",
            "cd app",
            "npm ci --omit=dev",
            "pm2 restart backend || pm2 start src/server.js --name backend"
          ]' \
          --query "Command.CommandId" \
          --output text)

        echo "Command ID: $COMMAND_ID"

        aws ssm list-command-invocations \
          --command-id "$COMMAND_ID" \
          --details