name: Employee Management CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Verify Node Version
        run: |
          node -v
          npm -v
      - name: Install frontend Dependencies
        working-directory: app/frontend
        run: npm install
      
      - name: Build Frontend
        working-directory: app/frontend
        run: npm run build

      - name: Zip build
        working-directory: app/frontend
        run: zip -r ../../frontend.zip dist
        
      - name: Verify ZIP
        run: |
         pwd
         ls -lh

      - name: Upload to S3
        run: |
         aws s3 cp app/frontend/frontend.zip s3://employeeapplicationdst/frontend.zip